services:
  iot-api:
    build: ./api
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    restart: unless-stopped
    networks:
      - iot-api-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - iot-api
    networks:
      - iot-api-network
    
networks:
  iot-api-network:
    driver: bridge