# Używamy oficjalnego obrazu Python
FROM python:3.10-slim

# Ustawiamy katalog roboczy w kontenerze
WORKDIR /app

# Kopiujemy requirements.txt
COPY requirements.txt .

# Instalujemy zależności
RUN pip install --no-cache-dir -r requirements.txt

# Kopiujemy kod aplikacji
COPY . .

# Eksponujemy port 5000
EXPOSE 5000

# Ustawiamy zmienne środowiskowe
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

# Uruchamiamy aplikację z Gunicorn
CMD ["gunicorn", "--config", "gunicorn.conf.py", "app:app"]